In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
## One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
    

[[2219, 9178, 5398, 8279],
 [2219, 9178, 5398, 1476],
 [2219, 6725, 5398, 8164],
 [9434, 1321, 4495, 8939, 6097],
 [9434, 1321, 4495, 8939, 8257],
 [3829, 2219, 948, 5398, 8890],
 [5961, 1649, 1067, 8939]]

In [8]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2219 9178 5398 8279]
 [   0    0    0    0 2219 9178 5398 1476]
 [   0    0    0    0 2219 6725 5398 8164]
 [   0    0    0 9434 1321 4495 8939 6097]
 [   0    0    0 9434 1321 4495 8939 8257]
 [   0    0    0 3829 2219  948 5398 8890]
 [   0    0    0    0 5961 1649 1067 8939]]


In [11]:
## feature representation
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length,input_shape=(sent_length,)))
model.compile('adam','mse')


In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[-0.00842527, -0.02877665, -0.01948139,  0.04691702,
          0.00374849, -0.01730348, -0.02522917, -0.01675456,
         -0.04759561, -0.01766516],
        [-0.00842527, -0.02877665, -0.01948139,  0.04691702,
          0.00374849, -0.01730348, -0.02522917, -0.01675456,
         -0.04759561, -0.01766516],
        [-0.00842527, -0.02877665, -0.01948139,  0.04691702,
          0.00374849, -0.01730348, -0.02522917, -0.01675456,
         -0.04759561, -0.01766516],
        [-0.00842527, -0.02877665, -0.01948139,  0.04691702,
          0.00374849, -0.01730348, -0.02522917, -0.01675456,
         -0.04759561, -0.01766516],
        [ 0.01309112, -0.00346874, -0.03144194, -0.0413327 ,
         -0.01828403,  0.00657424,  0.01751454, -0.04010935,
         -0.0390654 , -0.02531177],
        [-0.0344363 ,  0.00118407, -0.02150058,  0.04046159,
          0.00867618, -0.00805998, -0.04601176,  0.034396  ,
          0.01286692, -0.02070931],
        [-0.03685869, -0.02759743,  0.01349903, -0.0

array([   0,    0,    0,    0, 2219, 9178, 5398, 8279], dtype=int32)